# Generated by Django 4.2.18 on 2025-01-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchName', models.CharField(blank=True, max_length=50, null=True)),
                ('BatchYear', models.CharField(blank=True, max_length=50, null=True)),
                ('BatchStartYear', models.CharField(blank=True, max_length=50, null=True)),
                ('BatchEndYear', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(blank=True, max_length=50, null=True)),
                ('Latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Location_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Year', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Location_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Password', models.CharField(blank=True, max_length=50, null=True)),
                ('Type', models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('class_teacher', 'Class Teacher')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(blank=True, max_length=50, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('BatchName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.batchtable')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(blank=True, max_length=50, null=True)),
                ('Course', models.CharField(blank=True, max_length=50, null=True)),
                ('Year_of_Syllabus', models.DateField(blank=True, null=True)),
                ('Semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.semestertable')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone_number', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.departmentstable')),
                ('LOGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.logintable')),
                ('SubjectName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.subjectstable')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(blank=True, max_length=10, null=True)),
                ('Period', models.CharField(blank=True, max_length=20, null=True)),
                ('StartTime', models.TimeField(blank=True, max_length=50, null=True)),
                ('EndTime', models.TimeField(blank=True, max_length=50, null=True)),
                ('ClassName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.classtable')),
                ('SubjectName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.subjectstable')),
                ('TeacherName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.teachertable')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherNoticeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoticeName', models.CharField(blank=True, max_length=50, null=True)),
                ('NoticeContent', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('FileAttachment', models.FileField(blank=True, null=True, upload_to='File/')),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.departmentstable')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(blank=True, max_length=50, null=True)),
                ('Admission_no', models.CharField(blank=True, max_length=50, null=True)),
                ('BatchYear', models.CharField(blank=True, max_length=50, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('Blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('Guardian_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Guardian_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('Guardian_phone', models.BigIntegerField(blank=True, null=True)),
                ('Course', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone_number', models.BigIntegerField(blank=True, null=True)),
                ('ClassName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.classtable')),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.departmentstable')),
                ('LOGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.logintable')),
                ('Semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.semestertable')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNoticeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notice_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Notice_Content', models.TextField(blank=True, max_length=1000, null=True)),
                ('File_Attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('BatchName', models.ManyToManyField(to='SynChronisApp.batchtable')),
            ],
        ),
        migrations.CreateModel(
            name='NotesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.CharField(blank=True, max_length=50, null=True)),
                ('Class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.classtable')),
                ('SubjectName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.subjectstable')),
                ('Teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.teachertable')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplicationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Reason', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('StudentName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.studenttable')),
            ],
        ),
        migrations.AddField(
            model_name='classtable',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.departmentstable'),
        ),
        migrations.AddField(
            model_name='classtable',
            name='Semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.semestertable'),
        ),
        migrations.AddField(
            model_name='classtable',
            name='TeacherName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.teachertable'),
        ),
        migrations.AddField(
            model_name='batchtable',
            name='ClassName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.classtable'),
        ),
        migrations.CreateModel(
            name='AttendanceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Attendance', models.IntegerField(blank=True, null=True)),
                ('StudentName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.studenttable')),
            ],
        ),
    ]
