# Generated by Django 4.2.18 on 2025-01-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='Course',
        ),
        migrations.AddField(
            model_name='departmentstable',
            name='Courses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjectstable',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.departmentstable'),
        ),
    ]
