# Generated by Django 4.2.18 on 2025-02-02 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SynChronisApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttable',
            old_name='Course',
            new_name='Register_no',
        ),
        migrations.RemoveField(
            model_name='locationtable',
            name='Location_name',
        ),
        migrations.RemoveField(
            model_name='locationtable',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='locationtable',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='semestertable',
            name='BatchName',
        ),
        migrations.AddField(
            model_name='batchtable',
            name='Semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.semestertable'),
        ),
        migrations.AddField(
            model_name='classtable',
            name='Radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationtable',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentnoticetable',
            name='Notice_Type',
            field=models.CharField(blank=True, choices=[('HN', 'Holiday Notice'), ('EN', 'Exam Notice'), ('FN', 'Function Notice'), ('ON', 'Other Notice')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='CourseName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.subjectstable'),
        ),
        migrations.AddField(
            model_name='subjectstable',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.departmentstable'),
        ),
        migrations.AddField(
            model_name='subjectstable',
            name='Subject_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetabletable',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetabletable',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectstable',
            name='Year_of_Syllabus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='teachernoticetable',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='teachertable',
            name='SubjectName',
        ),
        migrations.AlterField(
            model_name='timetabletable',
            name='TeacherName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SynChronisApp.teachertable'),
        ),
        migrations.AlterUniqueTogether(
            name='timetabletable',
            unique_together={('ClassName', 'day', 'period')},
        ),
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=50, null=True)),
                ('CourseDuration', models.CharField(blank=True, max_length=50, null=True)),
                ('CourseDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('CourseCode', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.departmentstable')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('principal_name', models.CharField(max_length=100)),
                ('principal_contact', models.CharField(max_length=15)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='timetabletable',
            name='Day',
        ),
        migrations.RemoveField(
            model_name='timetabletable',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='timetabletable',
            name='Period',
        ),
        migrations.RemoveField(
            model_name='timetabletable',
            name='StartTime',
        ),
        migrations.AddField(
            model_name='locationtable',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjectstable',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.coursetable'),
        ),
        migrations.AddField(
            model_name='teachernoticetable',
            name='Department',
            field=models.ManyToManyField(to='SynChronisApp.departmentstable'),
        ),
        migrations.AddField(
            model_name='teachertable',
            name='SubjectName',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='SynChronisApp.subjectstable'),
        ),
        migrations.AddField(
            model_name='timetabletable',
            name='day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='timetabletable',
            name='period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
