# Generated by Django 4.2.18 on 2025-01-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0002_remove_studenttable_course_departmentstable_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('principal_name', models.CharField(max_length=255)),
                ('principal_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
