# Generated by Django 4.2.18 on 2025-01-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0003_collegedetailstable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentstable',
            name='Courses',
        ),
        migrations.AddField(
            model_name='studenttable',
            name='CourseName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.subjectstable'),
        ),
        migrations.AddField(
            model_name='subjectstable',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.departmentstable'),
        ),
        migrations.AddField(
            model_name='subjectstable',
            name='Subject_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.departmentstable')),
            ],
        ),
        migrations.AddField(
            model_name='departmentstable',
            name='CourseName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.coursetable'),
        ),
        migrations.AlterField(
            model_name='subjectstable',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.coursetable'),
        ),
    ]
