# Generated by Django 4.2.18 on 2025-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0003_alter_timetabletable_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetabletable',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetabletable',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
