# Generated by Django 4.2.18 on 2025-02-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0009_passwordresetotp_delete_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='Username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.logintable'),
        ),
    ]
