# Generated by Django 4.2.18 on 2025-02-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0010_remove_passwordresetotp_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='Password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
