# Generated by Django 4.2.18 on 2025-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0013_remove_registrationotp_user_registrationotp_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationotp',
            old_name='Username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='registrationotp',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
