# Generated by Django 4.2.18 on 2025-02-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0014_rename_username_registrationotp_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationotp',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registrationotp',
            name='password',
        ),
    ]
