# Generated by Django 5.1.6 on 2025-02-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0015_remove_registrationotp_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='CourseName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.coursetable'),
        ),
    ]
