# Generated by Django 5.1.6 on 2025-02-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0016_alter_studenttable_coursename'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestertable',
            name='BatchName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.batchtable'),
        ),
    ]
