# Generated by Django 5.1.6 on 2025-02-14 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0017_semestertable_batchname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentnoticetable',
            name='BatchName',
        ),
        migrations.RemoveField(
            model_name='semestertable',
            name='BatchName',
        ),
        migrations.RemoveField(
            model_name='classtable',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='classtable',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='subjectstable',
            name='Course',
        ),
        migrations.AddField(
            model_name='semestertable',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.coursetable'),
        ),
        migrations.DeleteModel(
            name='BatchTable',
        ),
    ]
