# Generated by Django 4.2.19 on 2025-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0020_subjectstable_subjecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtable',
            name='ClassType',
            field=models.CharField(blank=True, choices=[('Class Room', 'Class Room'), ('Computer Lab', 'Computer Lab'), ('Electronics Lab', 'Electronics Lab'), ('Physics Lab', 'Physics Lab'), ('Chemistry Lab', 'Chemistry Lab'), ('Biology Lab', 'Biology Lab'), ('Maths Lab', 'Maths Lab'), ('Library', 'Library'), ('Auditorium', 'Auditorium'), ('Seminar Hall', 'Seminar Hall')], max_length=50, null=True),
        ),
    ]
